import { existsSync, readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, resolve } from "path";
import type { ProjectConfig, GeneratedFile } from "./types.js";

export function generateDockerfile(config: ProjectConfig, projectPath: string): GeneratedFile {
  let content: string;

  switch (config.runtime) {
    case "node":
      content = generateNodeDockerfile(config);
      break;
    case "python":
      content = generatePythonDockerfile(config);
      break;
    case "go":
      content = generateGoDockerfile(config);
      break;
    case "rust":
      content = generateRustDockerfile(config);
      break;
    default:
      content = generateStaticDockerfile(config);
  }

  return {
    path: "Dockerfile",
    content,
    description: `Dockerfile for ${config.framework} (${config.runtime})`,
  };
}

export function generateDockerCompose(config: ProjectConfig): GeneratedFile {
  const services: string[] = [
    `version: "3.9"`,
    "",
    "services:",
    "  app:",
    "    build: .",
    `    ports:`,
    `      - "${config.port}:${config.port}"`,
    "    environment:",
  ];

  for (const env of config.envVars) {
    services.push(`      - ${env}=\${${env}}`);
  }

  services.push("    restart: unless-stopped");

  if (config.hasDatabase) {
    services.push("");
    services.push("  db:");
    services.push("    image: postgres:16-alpine");
    services.push("    environment:");
    services.push("      POSTGRES_USER: nexusforge");
    services.push("      POSTGRES_PASSWORD: \${DB_PASSWORD:-changeme}");
    services.push("      POSTGRES_DB: nexusforge");
    services.push("    ports:");
    services.push('      - "5432:5432"');
    services.push("    volumes:");
    services.push("      - pgdata:/var/lib/postgresql/data");
    services.push("    restart: unless-stopped");
    services.push("");
    services.push("  redis:");
    services.push("    image: redis:7-alpine");
    services.push("    ports:");
    services.push('      - "6379:6379"');
    services.push("    restart: unless-stopped");
    services.push("");
    services.push("volumes:");
    services.push("  pgdata:");
  }

  return {
    path: "docker-compose.yml",
    content: services.join("\n"),
    description: "Docker Compose configuration with all services",
  };
}

export function optimizeBuild(config: ProjectConfig, projectPath: string): { optimizations: string[]; savings: string } {
  const optimizations: string[] = [];
  let estimatedSavings = 0;

  if (config.runtime === "node") {
    const pkgPath = join(projectPath, "package.json");
    if (existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
        const devDeps = Object.keys(pkg.devDependencies || {});
        if (devDeps.length > 10) {
          optimizations.push(`Prune ${devDeps.length} dev dependencies in production`);
          estimatedSavings += devDeps.length * 2;
        }
      } catch { /* continue */ }
    }

    if (config.type === "nextjs") {
      optimizations.push("Enable Next.js standalone output mode");
      estimatedSavings += 30;
      optimizations.push("Enable image optimization with sharp");
      estimatedSavings += 10;
    }

    optimizations.push("Multi-stage Docker build to reduce image size");
    estimatedSavings += 40;
  }

  if (config.runtime === "python") {
    optimizations.push("Use slim base image (python:3.12-slim)");
    estimatedSavings += 50;
    optimizations.push("Install only production dependencies");
    estimatedSavings += 20;
  }

  if (config.runtime === "go") {
    optimizations.push("Use scratch base image for minimal binary");
    estimatedSavings += 90;
    optimizations.push("Strip debug symbols with -ldflags");
    estimatedSavings += 5;
  }

  if (config.runtime === "rust") {
    optimizations.push("Use multi-stage build with cargo-chef");
    estimatedSavings += 60;
    optimizations.push("Enable release profile optimizations");
    estimatedSavings += 10;
  }

  return {
    optimizations,
    savings: `~${estimatedSavings}% smaller image`,
  };
}

function generateNodeDockerfile(config: ProjectConfig): string {
  const pm = config.packageManager;
  const installCmd =
    pm === "bun" ? "bun install --frozen-lockfile" :
    pm === "pnpm" ? "pnpm install --frozen-lockfile" :
    pm === "yarn" ? "yarn install --frozen-lockfile" :
    "npm ci";

  const lockFile =
    pm === "bun" ? "bun.lock*" :
    pm === "pnpm" ? "pnpm-lock.yaml" :
    pm === "yarn" ? "yarn.lock" :
    "package-lock.json";

  const baseImage = pm === "bun" ? "oven/bun:1" : `node:${config.runtimeVersion}-alpine`;

  return [
    `# Generated by NexusForge Deployer`,
    `FROM ${baseImage} AS base`,
    "",
    "# Stage 1: Install dependencies",
    `FROM base AS deps`,
    "WORKDIR /app",
    `COPY package.json ${lockFile} ./`,
    `RUN ${installCmd}`,
    "",
    "# Stage 2: Build",
    "FROM base AS builder",
    "WORKDIR /app",
    "COPY --from=deps /app/node_modules ./node_modules",
    "COPY . .",
    `RUN ${pm} run build`,
    "",
    "# Stage 3: Production",
    "FROM base AS runner",
    "WORKDIR /app",
    "ENV NODE_ENV=production",
    "",
    config.type === "nextjs"
      ? [
          "COPY --from=builder /app/public ./public",
          "COPY --from=builder /app/.next/standalone ./",
          "COPY --from=builder /app/.next/static ./.next/static",
        ].join("\n")
      : [
          "COPY --from=builder /app/node_modules ./node_modules",
          `COPY --from=builder /app/${config.outputDir} ./${config.outputDir}`,
          "COPY --from=builder /app/package.json ./package.json",
        ].join("\n"),
    "",
    `EXPOSE ${config.port}`,
    `CMD ["${pm === "bun" ? "bun" : "node"}", "${config.type === "nextjs" ? "server.js" : "dist/index.js"}"]`,
  ].join("\n");
}

function generatePythonDockerfile(config: ProjectConfig): string {
  return [
    "# Generated by NexusForge Deployer",
    `FROM python:${config.runtimeVersion}-slim AS base`,
    "",
    "WORKDIR /app",
    "",
    "# Install system dependencies",
    "RUN apt-get update && apt-get install -y --no-install-recommends \\",
    "    build-essential \\",
    "    && rm -rf /var/lib/apt/lists/*",
    "",
    "# Install Python dependencies",
    "COPY requirements.txt .",
    "RUN pip install --no-cache-dir -r requirements.txt",
    "",
    "# Copy application code",
    "COPY . .",
    "",
    `EXPOSE ${config.port}`,
    "",
    config.type === "fastapi"
      ? `CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${config.port}"]`
      : `CMD ["python", "manage.py", "runserver", "0.0.0.0:${config.port}"]`,
  ].join("\n");
}

function generateGoDockerfile(config: ProjectConfig): string {
  return [
    "# Generated by NexusForge Deployer",
    `FROM golang:${config.runtimeVersion}-alpine AS builder`,
    "",
    "WORKDIR /app",
    "COPY go.mod go.sum ./",
    "RUN go mod download",
    "",
    "COPY . .",
    'RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/server .',
    "",
    "# Production: scratch for minimal image",
    "FROM scratch",
    "COPY --from=builder /app/server /server",
    "COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/",
    "",
    `EXPOSE ${config.port}`,
    'CMD ["/server"]',
  ].join("\n");
}

function generateRustDockerfile(config: ProjectConfig): string {
  return [
    "# Generated by NexusForge Deployer",
    `FROM rust:${config.runtimeVersion} AS builder`,
    "",
    "WORKDIR /app",
    "COPY Cargo.toml Cargo.lock ./",
    "",
    "# Cache dependencies",
    "RUN mkdir src && echo 'fn main() {}' > src/main.rs",
    "RUN cargo build --release && rm -rf src",
    "",
    "# Build actual application",
    "COPY . .",
    "RUN cargo build --release",
    "",
    "# Production: minimal image",
    "FROM debian:bookworm-slim",
    "RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*",
    "COPY --from=builder /app/target/release/app /usr/local/bin/app",
    "",
    `EXPOSE ${config.port}`,
    'CMD ["app"]',
  ].join("\n");
}

function generateStaticDockerfile(config: ProjectConfig): string {
  return [
    "# Generated by NexusForge Deployer",
    "FROM nginx:alpine",
    "COPY . /usr/share/nginx/html",
    "EXPOSE 80",
    'CMD ["nginx", "-g", "daemon off;"]',
  ].join("\n");
}

export function writeGeneratedFiles(files: GeneratedFile[], outputDir: string): void {
  for (const file of files) {
    const fullPath = resolve(outputDir, file.path);
    const dir = join(fullPath, "..");
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    writeFileSync(fullPath, file.content, "utf-8");
  }
}