import { resolve } from "path";
import type { IaCConfig, IaCResult, GeneratedFile } from "./types.js";
import { writeGeneratedFiles } from "./builder.js";

export function generateIaC(config: IaCConfig): IaCResult {
  switch (config.provider) {
    case "terraform":
      return generateTerraform(config);
    case "pulumi":
      return generatePulumi(config);
    case "docker-compose":
      return generateDockerComposeIaC(config);
    case "kubernetes":
      return generateKubernetes(config);
    default:
      return generateTerraform(config);
  }
}

function generateTerraform(config: IaCConfig): IaCResult {
  const files: GeneratedFile[] = [];
  const region = "us-east-1";

  files.push({
    path: "infra/main.tf",
    content: [
      "# Generated by NexusForge Deployer",
      `# Cloud: ${config.cloudProvider} | Stage: ${config.stage}`,
      "",
      "terraform {",
      '  required_version = ">= 1.5"',
      "  required_providers {",
      "    aws = {",
      '      source  = "hashicorp/aws"',
      '      version = "~> 5.0"',
      "    }",
      "  }",
      "  backend \"s3\" {",
      `    bucket = "nexusforge-tf-state"`,
      `    key    = "${config.stage}/terraform.tfstate"`,
      `    region = "${region}"`,
      "  }",
      "}",
      "",
      "provider \"aws\" {",
      `  region = var.aws_region`,
      "}",
      "",
      "module \"networking\" {",
      '  source = "./modules/networking"',
      "  environment = var.environment",
      "}",
      "",
      "module \"compute\" {",
      '  source = "./modules/compute"',
      "  environment    = var.environment",
      "  vpc_id         = module.networking.vpc_id",
      "  subnet_ids     = module.networking.private_subnet_ids",
      `  container_port = ${config.project.port}`,
      "}",
    ].join("\n"),
    description: "Main Terraform configuration",
  });

  files.push({
    path: "infra/variables.tf",
    content: [
      "# Generated by NexusForge Deployer",
      "",
      'variable "aws_region" {',
      '  description = "AWS region"',
      "  type        = string",
      `  default     = "${region}"`,
      "}",
      "",
      'variable "environment" {',
      '  description = "Deployment environment"',
      "  type        = string",
      `  default     = "${config.stage}"`,
      "}",
      "",
      'variable "app_name" {',
      '  description = "Application name"',
      "  type        = string",
      '  default     = "nexusforge-app"',
      "}",
      "",
      'variable "container_port" {',
      '  description = "Container port"',
      "  type        = number",
      `  default     = ${config.project.port}`,
      "}",
    ].join("\n"),
    description: "Terraform input variables",
  });

  files.push({
    path: "infra/outputs.tf",
    content: [
      "# Generated by NexusForge Deployer",
      "",
      'output "app_url" {',
      '  description = "Application URL"',
      "  value       = module.compute.app_url",
      "}",
      "",
      'output "vpc_id" {',
      '  description = "VPC ID"',
      "  value       = module.networking.vpc_id",
      "}",
    ].join("\n"),
    description: "Terraform output definitions",
  });

  if (config.features.includes("database")) {
    files.push({
      path: "infra/modules/database/main.tf",
      content: [
        "# Generated by NexusForge Deployer",
        "",
        'resource "aws_db_instance" "main" {',
        '  identifier        = "${var.app_name}-${var.environment}"',
        '  engine            = "postgres"',
        '  engine_version    = "16"',
        '  instance_class    = "db.t3.micro"',
        "  allocated_storage = 20",
        "",
        '  db_name  = "nexusforge"',
        '  username = "nexusforge"',
        '  password = var.db_password',
        "",
        "  skip_final_snapshot = true",
        "",
        "  tags = {",
        "    Environment = var.environment",
        '    ManagedBy   = "NexusForge"',
        "  }",
        "}",
      ].join("\n"),
      description: "RDS PostgreSQL module",
    });
  }

  return {
    files,
    provider: "terraform",
    cloudProvider: config.cloudProvider,
    commands: [
      "cd infra",
      "terraform init",
      `terraform plan -var-file=environments/${config.stage}.tfvars`,
      `terraform apply -var-file=environments/${config.stage}.tfvars -auto-approve`,
    ],
  };
}

function generatePulumi(config: IaCConfig): IaCResult {
  const files: GeneratedFile[] = [];

  files.push({
    path: "infra/Pulumi.yaml",
    content: [
      "# Generated by NexusForge Deployer",
      "name: nexusforge-infra",
      `runtime: nodejs`,
      "description: Infrastructure managed by NexusForge Deployer",
    ].join("\n"),
    description: "Pulumi project configuration",
  });

  files.push({
    path: "infra/index.ts",
    content: [
      '// Generated by NexusForge Deployer',
      'import * as pulumi from "@pulumi/pulumi";',
      "",
      'const config = new pulumi.Config();',
      'const environment = config.require("environment");',
      "",
      `// Cloud provider: ${config.cloudProvider}`,
      `// Stage: ${config.stage}`,
      "",
      "export const appUrl = `https://nexusforge-app.example.com`;",
    ].join("\n"),
    description: "Pulumi infrastructure code",
  });

  return {
    files,
    provider: "pulumi",
    cloudProvider: config.cloudProvider,
    commands: [
      "cd infra",
      "npm install",
      `pulumi stack select ${config.stage}`,
      "pulumi up --yes",
    ],
  };
}

function generateDockerComposeIaC(config: IaCConfig): IaCResult {
  const files: GeneratedFile[] = [];
  const services: string[] = [
    "# Generated by NexusForge Deployer",
    'version: "3.9"',
    "",
    "services:",
    "  app:",
    "    build:",
    "      context: .",
    "      dockerfile: Dockerfile",
    `    ports:`,
    `      - "${config.project.port}:${config.project.port}"`,
    "    environment:",
    `      - NODE_ENV=${config.stage === "production" ? "production" : "development"}`,
    "    restart: unless-stopped",
    "    networks:",
    "      - app-network",
  ];

  if (config.features.includes("database")) {
    services.push(
      "",
      "  postgres:",
      "    image: postgres:16-alpine",
      "    environment:",
      "      POSTGRES_USER: nexusforge",
      "      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}",
      "      POSTGRES_DB: nexusforge",
      "    volumes:",
      "      - pgdata:/var/lib/postgresql/data",
      "    ports:",
      '      - "5432:5432"',
      "    networks:",
      "      - app-network",
      "    restart: unless-stopped"
    );
  }

  if (config.features.includes("monitoring")) {
    services.push(
      "",
      "  prometheus:",
      "    image: prom/prometheus",
      "    ports:",
      '      - "9090:9090"',
      "    volumes:",
      "      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml",
      "    networks:",
      "      - app-network"
    );
  }

  services.push(
    "",
    "networks:",
    "  app-network:",
    "    driver: bridge",
    "",
    "volumes:"
  );

  if (config.features.includes("database")) {
    services.push("  pgdata:");
  }

  files.push({
    path: `docker-compose.${config.stage}.yml`,
    content: services.join("\n"),
    description: `Docker Compose for ${config.stage}`,
  });

  return {
    files,
    provider: "docker-compose",
    cloudProvider: config.cloudProvider,
    commands: [
      `docker compose -f docker-compose.${config.stage}.yml up -d`,
    ],
  };
}

function generateKubernetes(config: IaCConfig): IaCResult {
  const files: GeneratedFile[] = [];

  files.push({
    path: "k8s/deployment.yaml",
    content: [
      "# Generated by NexusForge Deployer",
      "apiVersion: apps/v1",
      "kind: Deployment",
      "metadata:",
      "  name: nexusforge-app",
      "  labels:",
      "    app: nexusforge-app",
      `    environment: ${config.stage}`,
      "spec:",
      "  replicas: 2",
      "  selector:",
      "    matchLabels:",
      "      app: nexusforge-app",
      "  template:",
      "    metadata:",
      "      labels:",
      "        app: nexusforge-app",
      "    spec:",
      "      containers:",
      "        - name: app",
      "          image: nexusforge-app:latest",
      "          ports:",
      `            - containerPort: ${config.project.port}`,
      "          resources:",
      "            requests:",
      '              memory: "128Mi"',
      '              cpu: "250m"',
      "            limits:",
      '              memory: "256Mi"',
      '              cpu: "500m"',
      "          livenessProbe:",
      "            httpGet:",
      "              path: /health",
      `              port: ${config.project.port}`,
      "            initialDelaySeconds: 15",
      "            periodSeconds: 10",
    ].join("\n"),
    description: "Kubernetes Deployment manifest",
  });

  files.push({
    path: "k8s/service.yaml",
    content: [
      "# Generated by NexusForge Deployer",
      "apiVersion: v1",
      "kind: Service",
      "metadata:",
      "  name: nexusforge-app",
      "spec:",
      "  type: ClusterIP",
      "  selector:",
      "    app: nexusforge-app",
      "  ports:",
      "    - protocol: TCP",
      "      port: 80",
      `      targetPort: ${config.project.port}`,
    ].join("\n"),
    description: "Kubernetes Service manifest",
  });

  files.push({
    path: "k8s/ingress.yaml",
    content: [
      "# Generated by NexusForge Deployer",
      "apiVersion: networking.k8s.io/v1",
      "kind: Ingress",
      "metadata:",
      "  name: nexusforge-app",
      "  annotations:",
      '    nginx.ingress.kubernetes.io/ssl-redirect: "true"',
      "spec:",
      "  ingressClassName: nginx",
      "  rules:",
      "    - host: app.nexusforge.dev",
      "      http:",
      "        paths:",
      "          - path: /",
      "            pathType: Prefix",
      "            backend:",
      "              service:",
      "                name: nexusforge-app",
      "                port:",
      "                  number: 80",
    ].join("\n"),
    description: "Kubernetes Ingress manifest",
  });

  return {
    files,
    provider: "kubernetes",
    cloudProvider: config.cloudProvider,
    commands: [
      "kubectl apply -f k8s/deployment.yaml",
      "kubectl apply -f k8s/service.yaml",
      "kubectl apply -f k8s/ingress.yaml",
    ],
  };
}

export function writeIaCFiles(result: IaCResult, outputDir: string): void {
  writeGeneratedFiles(result.files, outputDir);
}