import type { PipelineConfig, PipelineResult, GeneratedFile } from "./types.js";
import { writeGeneratedFiles } from "./builder.js";

export function generatePipeline(config: PipelineConfig): PipelineResult {
  switch (config.ciProvider) {
    case "github-actions":
      return generateGitHubActions(config);
    case "gitlab-ci":
      return generateGitLabCI(config);
    case "jenkins":
      return generateJenkinsfile(config);
    case "circleci":
      return generateCircleCI(config);
    default:
      return generateGitHubActions(config);
  }
}

function generateGitHubActions(config: PipelineConfig): PipelineResult {
  const files: GeneratedFile[] = [];
  const jobs: string[] = [];
  const pm = config.project.packageManager;
  const nodeVer = config.project.runtimeVersion;

  if (config.features.includes("lint")) {
    jobs.push(
      "  lint:", "    runs-on: ubuntu-latest", "    steps:",
      "      - uses: actions/checkout@v4",
      "      - uses: actions/setup-node@v4", "        with:",
      `          node-version: '${nodeVer}'`,
      `      - run: ${pm} install`, `      - run: ${pm} run lint`, ""
    );
  }

  if (config.features.includes("test")) {
    jobs.push(
      "  test:", "    runs-on: ubuntu-latest",
      config.features.includes("lint") ? "    needs: lint" : "",
      "    steps:", "      - uses: actions/checkout@v4",
      "      - uses: actions/setup-node@v4", "        with:",
      `          node-version: '${nodeVer}'`,
      `      - run: ${pm} install`, `      - run: ${pm} run test`, ""
    );
  }

  if (config.features.includes("build")) {
    jobs.push(
      "  build:", "    runs-on: ubuntu-latest",
      config.features.includes("test") ? "    needs: test" : "",
      "    steps:", "      - uses: actions/checkout@v4",
      "      - uses: actions/setup-node@v4", "        with:",
      `          node-version: '${nodeVer}'`,
      `      - run: ${pm} install`, `      - run: ${config.project.buildCommand}`, ""
    );
  }

  if (config.features.includes("security-scan")) {
    jobs.push(
      "  security:", "    runs-on: ubuntu-latest", "    steps:",
      "      - uses: actions/checkout@v4",
      "      - name: Run NexusForge Security Scanner",
      "        run: npx @nexusforge/scanner scan --path .", ""
    );
  }

  const workflow = [
    "# Generated by NexusForge Deployer",
    "name: CI/CD Pipeline", "",
    "on:", "  push:", "    branches: [main, develop]",
    "  pull_request:", "    branches: [main]", "",
    "jobs:", ...jobs,
  ];

  files.push({
    path: ".github/workflows/ci-cd.yml",
    content: workflow.filter(Boolean).join("\n"),
    description: "GitHub Actions CI/CD workflow",
  });

  return { files, ciProvider: "github-actions", stages: config.stages };
}

function generateGitLabCI(config: PipelineConfig): PipelineResult {
  const files: GeneratedFile[] = [];
  const pm = config.project.packageManager;
  const stages = config.features
    .filter((f) => ["lint", "test", "build"].includes(f));

  const lines = [
    "# Generated by NexusForge Deployer",
    "stages:", ...stages.map((s) => `  - ${s}`), "",
    `image: node:${config.project.runtimeVersion}`, "",
    "cache:", "  paths:", "    - node_modules/", "",
  ];

  if (config.features.includes("lint")) {
    lines.push("lint:", "  stage: lint", "  script:",
      `    - ${pm} install`, `    - ${pm} run lint`, "");
  }

  if (config.features.includes("test")) {
    lines.push("test:", "  stage: test", "  script:",
      `    - ${pm} install`, `    - ${pm} run test`, "");
  }

  if (config.features.includes("build")) {
    lines.push("build:", "  stage: build", "  script:",
      `    - ${pm} install`, `    - ${config.project.buildCommand}`, "");
  }

  files.push({
    path: ".gitlab-ci.yml",
    content: lines.join("\n"),
    description: "GitLab CI/CD pipeline",
  });

  return { files, ciProvider: "gitlab-ci", stages: config.stages };
}

function generateJenkinsfile(config: PipelineConfig): PipelineResult {
  const stages: string[] = [];

  if (config.features.includes("build")) {
    stages.push(
      "    stage('Build') {", "      steps {",
      `        sh '${config.project.buildCommand}'`,
      "      }", "    }"
    );
  }

  if (config.features.includes("test")) {
    stages.push(
      "    stage('Test') {", "      steps {",
      `        sh '${config.project.packageManager} run test'`,
      "      }", "    }"
    );
  }

  const content = [
    "// Generated by NexusForge Deployer",
    "pipeline {", "  agent any", "  stages {",
    ...stages, "  }", "}",
  ];

  return {
    files: [{ path: "Jenkinsfile", content: content.join("\n"), description: "Jenkins pipeline" }],
    ciProvider: "jenkins",
    stages: config.stages,
  };
}

function generateCircleCI(config: PipelineConfig): PipelineResult {
  const content = [
    "# Generated by NexusForge Deployer",
    "version: 2.1", "",
    "jobs:", "  build-and-test:", "    docker:",
    `      - image: cimg/node:${config.project.runtimeVersion}`,
    "    steps:", "      - checkout",
    `      - run: ${config.project.packageManager} install`,
    `      - run: ${config.project.buildCommand}`, "",
    "workflows:", "  main:", "    jobs:",
    "      - build-and-test",
  ];

  return {
    files: [{ path: ".circleci/config.yml", content: content.join("\n"), description: "CircleCI pipeline" }],
    ciProvider: "circleci",
    stages: config.stages,
  };
}

export function writePipelineFiles(result: PipelineResult, outputDir: string): void {
  writeGeneratedFiles(result.files, outputDir);
}
