import type { Bug, AnalysisResult, AnalysisSummary, Fix } from "./types.js";
import { scanDirectory } from "./detector.js";
import { generateFixes } from "./fixer.js";

export async function analyze(
  projectPath: string,
  options: { fix?: boolean; ignore?: string[] } = {}
): Promise<AnalysisResult> {
  const startTime = Date.now();
  const results = scanDirectory(projectPath, options.ignore);

  const allBugs: Bug[] = results.flatMap((r) => r.bugs);
  let fixes: Fix[] = [];

  if (options.fix) {
    fixes = generateFixes(allBugs, projectPath);
  }

  const summary = calculateSummary(allBugs);

  return {
    projectPath,
    timestamp: new Date().toISOString(),
    duration: Date.now() - startTime,
    filesScanned: results.length,
    bugs: allBugs,
    fixes,
    summary,
  };
}

function calculateSummary(bugs: Bug[]): AnalysisSummary {
  const summary: AnalysisSummary = {
    totalBugs: bugs.length,
    critical: 0,
    errors: 0,
    warnings: 0,
    infos: 0,
    autoFixable: 0,
    healthScore: 100,
  };

  for (const bug of bugs) {
    switch (bug.severity) {
      case "critical": summary.critical++; break;
      case "error": summary.errors++; break;
      case "warning": summary.warnings++; break;
      case "info": summary.infos++; break;
    }
    if (bug.autoFixable) summary.autoFixable++;
  }

  summary.healthScore = Math.max(
    0,
    100 - summary.critical * 20 - summary.errors * 10 - summary.warnings * 3 - summary.infos * 0.5
  );

  return summary;
}

export function generateReport(result: AnalysisResult): string {
  let report = `# NexusForge Self-Healing Report\n\n`;
  report += `**Project:** ${result.projectPath}\n`;
  report += `**Scanned:** ${new Date(result.timestamp).toLocaleString()}\n`;
  report += `**Duration:** ${result.duration}ms\n`;
  report += `**Files Analyzed:** ${result.filesScanned}\n\n`;

  report += `## Health Score: ${result.summary.healthScore}/100\n\n`;

  report += `| Severity | Count |\n|----------|-------|\n`;
  report += `| 🔴 Critical | ${result.summary.critical} |\n`;
  report += `| 🟠 Error | ${result.summary.errors} |\n`;
  report += `| 🟡 Warning | ${result.summary.warnings} |\n`;
  report += `| 🔵 Info | ${result.summary.infos} |\n`;
  report += `| 🔧 Auto-fixable | ${result.summary.autoFixable} |\n\n`;

  if (result.bugs.length > 0) {
    report += `## Issues Found\n\n`;

    const grouped = groupBugsByFile(result.bugs);
    for (const [file, bugs] of Object.entries(grouped)) {
      report += `### 📄 ${file}\n\n`;
      for (const bug of bugs) {
        const emoji = bug.severity === "critical" ? "🔴" : bug.severity === "error" ? "🟠" : bug.severity === "warning" ? "🟡" : "🔵";
        report += `#### ${emoji} ${bug.id} — ${bug.message}\n`;
        report += `- **Line ${bug.line}** | ${bug.category} | ${bug.autoFixable ? "🔧 Auto-fixable" : ""}\n`;
        if (bug.suggestion) report += `- **Suggestion:** ${bug.suggestion}\n`;
        report += `\n\`\`\`\n${bug.snippet}\n\`\`\`\n\n`;
      }
    }
  }

  if (result.fixes.length > 0) {
    report += `## Applied Fixes\n\n`;
    for (const fix of result.fixes) {
      report += `### 🔧 ${fix.bugId}\n`;
      report += `- **File:** ${fix.file}\n`;
      report += `- **Confidence:** ${(fix.confidence * 100).toFixed(0)}%\n`;
      report += `- ${fix.description}\n\n`;
      report += `**Before:**\n\`\`\`\n${fix.original}\n\`\`\`\n\n`;
      report += `**After:**\n\`\`\`\n${fix.fixed}\n\`\`\`\n\n`;
    }
  }

  report += `---\n*Generated by [NexusForge Healer](https://github.com/0xgetz/nexusforge)*\n`;
  return report;
}

function groupBugsByFile(bugs: Bug[]): Record<string, Bug[]> {
  const grouped: Record<string, Bug[]> = {};
  for (const bug of bugs) {
    if (!grouped[bug.file]) grouped[bug.file] = [];
    grouped[bug.file].push(bug);
  }
  return grouped;
}