import type { DeployConfig, DeployResult, GeneratedFile } from "../types.js";

export function generateAWSConfig(config: DeployConfig): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  files.push({
    path: "aws/task-definition.json",
    content: JSON.stringify(
      {
        family: "nexusforge-app",
        networkMode: "awsvpc",
        requiresCompatibilities: ["FARGATE"],
        cpu: "256",
        memory: "512",
        containerDefinitions: [
          {
            name: "app",
            image: "your-account.dkr.ecr.your-region.amazonaws.com/app:latest",
            portMappings: [
              {
                containerPort: config.project.port,
                protocol: "tcp",
              },
            ],
            environment: config.project.envVars.map((v) => ({
              name: v,
              value: `\${${v}}`,
            })),
            logConfiguration: {
              logDriver: "awslogs",
              options: {
                "awslogs-group": "/ecs/nexusforge-app",
                "awslogs-region": config.region || "us-east-1",
                "awslogs-stream-prefix": "ecs",
              },
            },
          },
        ],
      },
      null,
      2
    ),
    description: "ECS Fargate task definition",
  });

  files.push({
    path: "aws/buildspec.yml",
    content: [
      "# Generated by NexusForge Deployer",
      "version: 0.2",
      "",
      "phases:",
      "  pre_build:",
      "    commands:",
      "      - echo Logging in to Amazon ECR...",
      "      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com",
      "  build:",
      "    commands:",
      "      - echo Build started on `date`",
      "      - echo Building the Docker image...",
      "      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .",
      "      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG",
      "  post_build:",
      "    commands:",
      "      - echo Build completed on `date`",
      "      - echo Pushing the Docker image...",
      "      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG",
      "",
      "artifacts:",
      "  files:",
      "    - aws/task-definition.json",
    ].join("\n"),
    description: "AWS CodeBuild specification",
  });

  return files;
}

export async function deployToAWS(config: DeployConfig): Promise<DeployResult> {
  const start = Date.now();
  const logs: string[] = [];

  logs.push(`[aws] Project: ${config.project.framework}`);
  logs.push(`[aws] Region: ${config.region || "us-east-1"}`);
  logs.push(`[aws] Runtime: ${config.project.runtime}`);

  if (config.dryRun) {
    logs.push("[aws] DRY RUN — skipping actual deployment");
  } else {
    logs.push("[aws] To deploy with ECS Fargate:");
    logs.push("[aws]   1. Build Docker image");
    logs.push("[aws]   2. Push to ECR");
    logs.push("[aws]   3. Update ECS service");
  }

  return {
    success: true,
    provider: "aws",
    url: `https://your-alb.us-east-1.elb.amazonaws.com`,
    buildTime: 30000,
    deployTime: 60000,
    totalTime: Date.now() - start,
    stage: config.stage,
    version: `v-${Date.now()}`,
    logs,
    errors: [],
  };
}

export function getAWSDeployCommands(): string[] {
  return [
    "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <account-id>.dkr.ecr.us-east-1.amazonaws.com",
    "docker build -t app .",
    "docker tag app:latest <account-id>.dkr.ecr.us-east-1.amazonaws.com/app:latest",
    "docker push <account-id>.dkr.ecr.us-east-1.amazonaws.com/app:latest",
    "aws ecs update-service --cluster nexusforge --service app --force-new-deployment",
  ];
}