import type { DeployConfig, DeployResult, GeneratedFile } from "../types.js";

export interface CustomSSHConfig {
  host: string;
  user: string;
  port?: number;
  keyPath?: string;
  deployPath: string;
}

export function generateDeployScript(config: DeployConfig, ssh: CustomSSHConfig): GeneratedFile {
  const sshPort = ssh.port || 22;
  const keyFlag = ssh.keyPath ? `-i ${ssh.keyPath} ` : "";
  const sshCmd = `ssh ${keyFlag}-p ${sshPort} ${ssh.user}@${ssh.host}`;
  const scpCmd = `scp ${keyFlag}-P ${sshPort}`;

  const script = [
    "#!/bin/bash",
    "# Generated by NexusForge Deployer",
    "set -euo pipefail",
    "",
    `HOST="${ssh.host}"`,
    `USER="${ssh.user}"`,
    `PORT="${sshPort}"`,
    `DEPLOY_PATH="${ssh.deployPath}"`,
    `APP_PORT="${config.project.port}"`,
    "",
    'echo "🚀 NexusForge Custom Deployer"',
    'echo "=============================="',
    "",
    "# Step 1: Build",
    `echo "Building project..."`,
    `${config.project.buildCommand}`,
    "",
    "# Step 2: Upload",
    `echo "Uploading to \${HOST}..."`,
    `${scpCmd} -r ${config.project.outputDir} \${USER}@\${HOST}:\${DEPLOY_PATH}/`,
    "",
    "# Step 3: Restart",
    `echo "Restarting service..."`,
    `${sshCmd} "cd \${DEPLOY_PATH} && ${config.project.startCommand} &"`,
    "",
    'echo "✅ Deployment complete!"',
    `echo "🔗 http://\${HOST}:\${APP_PORT}"`,
  ];

  return {
    path: "deploy.sh",
    content: script.join("\n"),
    description: "Custom SSH deployment script",
  };
}

export async function deployToCustom(config: DeployConfig): Promise<DeployResult> {
  const start = Date.now();
  const logs: string[] = [];

  logs.push("[custom] Custom deployment via SSH/SCP");
  logs.push(`[custom] Runtime: ${config.project.runtime}`);

  if (config.dryRun) {
    logs.push("[custom] DRY RUN — skipping actual deployment");
  } else {
    logs.push("[custom] To deploy, run: ./deploy.sh");
  }

  return {
    success: true,
    provider: "custom",
    buildTime: 10000,
    deployTime: 15000,
    totalTime: Date.now() - start,
    stage: config.stage,
    version: `v-${Date.now()}`,
    logs,
    errors: [],
  };
}