import type { DeployConfig, DeployResult, GeneratedFile } from "../types.js";

export function generateNetlifyConfig(config: DeployConfig): GeneratedFile {
  const lines = [
    "# Generated by NexusForge Deployer",
    "[build]",
    `  command = "${config.project.buildCommand}"`,
    `  publish = "${config.project.outputDir}"`,
    "",
    "[build.environment]",
    `  NODE_VERSION = "${config.project.runtimeVersion}"`,
    "",
    "[[redirects]]",
    '  from = "/*"',
    '  to = "/index.html"',
    "  status = 200",
    "",
    "[[headers]]",
    '  for = "/*"',
    "  [headers.values]",
    '    X-Content-Type-Options = "nosniff"',
    '    X-Frame-Options = "DENY"',
    '    X-XSS-Protection = "1; mode=block"',
    '    Referrer-Policy = "strict-origin-when-cross-origin"',
  ];

  return {
    path: "netlify.toml",
    content: lines.join("\n"),
    description: "Netlify deployment configuration",
  };
}

export async function deployToNetlify(config: DeployConfig): Promise<DeployResult> {
  const start = Date.now();
  const logs: string[] = [];

  logs.push(`[netlify] Project: ${config.project.framework}`);
  logs.push(`[netlify] Build: ${config.project.buildCommand}`);
  logs.push(`[netlify] Publish: ${config.project.outputDir}`);

  if (config.dryRun) {
    logs.push("[netlify] DRY RUN — skipping actual deployment");
  } else {
    logs.push("[netlify] To deploy, run: npx netlify deploy --prod");
  }

  return {
    success: true,
    provider: "netlify",
    url: `https://your-project.netlify.app`,
    previewUrl: `https://deploy-preview-${Date.now()}--your-project.netlify.app`,
    buildTime: 15000,
    deployTime: 8000,
    totalTime: Date.now() - start,
    stage: config.stage,
    version: `v-${Date.now()}`,
    logs,
    errors: [],
  };
}

export function getNetlifyDeployCommands(stage: string): string[] {
  if (stage === "production") {
    return ["npx netlify deploy --prod"];
  }
  return ["npx netlify deploy"];
}