import type { ScanResult, Severity } from "./types.js";

export function toJSON(result: ScanResult): string {
  return JSON.stringify(result, null, 2);
}

export function toMarkdown(result: ScanResult): string {
  const severityEmoji: Record<Severity, string> = {
    critical: "🔴",
    high: "🟠",
    medium: "🟡",
    low: "🔵",
    info: "⚪",
  };

  let md = `# NexusForge Security Report\n\n`;
  md += `**Project:** ${result.projectName}\n`;
  md += `**Scanned:** ${new Date(result.timestamp).toLocaleString()}\n`;
  md += `**Duration:** ${result.duration}ms\n`;
  md += `**Ecosystem:** ${result.ecosystem}\n\n`;

  md += `## Summary\n\n`;
  md += `| Metric | Value |\n|--------|-------|\n`;
  md += `| Security Score | **${result.summary.score}/100** |\n`;
  md += `| Total Dependencies | ${result.totalDependencies} |\n`;
  md += `| Vulnerable Packages | ${result.vulnerablePackages} |\n`;
  md += `| Total Vulnerabilities | ${result.summary.total} |\n\n`;

  md += `### Severity Breakdown\n\n`;
  md += `| Severity | Count |\n|----------|-------|\n`;
  md += `| ${severityEmoji.critical} Critical | ${result.summary.critical} |\n`;
  md += `| ${severityEmoji.high} High | ${result.summary.high} |\n`;
  md += `| ${severityEmoji.medium} Medium | ${result.summary.medium} |\n`;
  md += `| ${severityEmoji.low} Low | ${result.summary.low} |\n`;
  md += `| ${severityEmoji.info} Info | ${result.summary.info} |\n\n`;

  if (result.vulnerabilities.length > 0) {
    md += `## Vulnerabilities\n\n`;
    for (const vuln of result.vulnerabilities) {
      md += `### ${severityEmoji[vuln.severity]} ${vuln.id} — ${vuln.title}\n\n`;
      md += `- **Package:** \`${vuln.package}@${vuln.version}\`\n`;
      md += `- **Severity:** ${vuln.severity.toUpperCase()}`;
      if (vuln.cvss) md += ` (CVSS: ${vuln.cvss})`;
      md += `\n`;
      if (vuln.fixedIn) md += `- **Fix:** Upgrade to \`${vuln.fixedIn}\`\n`;
      if (vuln.cwe?.length) md += `- **CWE:** ${vuln.cwe.join(", ")}\n`;
      if (vuln.url) md += `- **Reference:** [${vuln.url}](${vuln.url})\n`;
      md += `\n${vuln.description}\n\n---\n\n`;
    }
  }

  const outdated = result.dependencies.filter((d) => d.outdated);
  if (outdated.length > 0) {
    md += `## Outdated Dependencies\n\n`;
    md += `| Package | Current | Latest |\n|---------|---------|--------|\n`;
    for (const dep of outdated) {
      md += `| ${dep.name} | ${dep.version} | ${dep.latest} |\n`;
    }
    md += `\n`;
  }

  md += `---\n*Generated by [NexusForge Scanner](https://github.com/0xgetz/nexusforge)*\n`;
  return md;
}

export function toHTML(result: ScanResult): string {
  const scoreColor =
    result.summary.score >= 80 ? "#10b981" :
    result.summary.score >= 60 ? "#f59e0b" :
    result.summary.score >= 40 ? "#f97316" : "#ef4444";

  const severityColor: Record<Severity, string> = {
    critical: "#ef4444",
    high: "#f97316",
    medium: "#f59e0b",
    low: "#3b82f6",
    info: "#9ca3af",
  };

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NexusForge Security Report — ${result.projectName}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0a0a0a; color: #e5e5e5; padding: 2rem; }
    .container { max-width: 900px; margin: 0 auto; }
    h1 { color: #10b981; font-size: 1.8rem; margin-bottom: 0.5rem; }
    h2 { color: #a3e635; font-size: 1.3rem; margin: 2rem 0 1rem; border-bottom: 1px solid #262626; padding-bottom: 0.5rem; }
    .meta { color: #737373; font-size: 0.85rem; margin-bottom: 2rem; }
    .score-ring { width: 120px; height: 120px; border-radius: 50%; border: 6px solid ${scoreColor}; display: flex; align-items: center; justify-content: center; margin: 1rem auto; }
    .score-value { font-size: 2rem; font-weight: bold; color: ${scoreColor}; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 1rem; margin: 1rem 0; }
    .stat { background: #171717; border: 1px solid #262626; border-radius: 8px; padding: 1rem; text-align: center; }
    .stat-value { font-size: 1.5rem; font-weight: bold; }
    .stat-label { font-size: 0.75rem; color: #737373; margin-top: 0.25rem; }
    .vuln-card { background: #171717; border: 1px solid #262626; border-radius: 8px; padding: 1rem; margin: 0.75rem 0; border-left: 4px solid; }
    .vuln-id { font-weight: bold; font-size: 0.9rem; }
    .vuln-pkg { color: #737373; font-size: 0.8rem; }
    .vuln-desc { font-size: 0.85rem; margin-top: 0.5rem; color: #a3a3a3; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.7rem; font-weight: 600; text-transform: uppercase; }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
    th, td { padding: 0.5rem; text-align: left; border-bottom: 1px solid #262626; font-size: 0.85rem; }
    th { color: #737373; font-weight: 600; }
    .footer { text-align: center; color: #525252; font-size: 0.75rem; margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #262626; }
  </style>
</head>
<body>
  <div class="container">
    <h1>⚡ NexusForge Security Report</h1>
    <div class="meta">${result.projectName} • ${new Date(result.timestamp).toLocaleString()} • ${result.ecosystem} • ${result.duration}ms</div>

    <div class="score-ring"><span class="score-value">${result.summary.score}</span></div>

    <div class="grid">
      <div class="stat"><div class="stat-value">${result.totalDependencies}</div><div class="stat-label">Dependencies</div></div>
      <div class="stat"><div class="stat-value" style="color:${severityColor.critical}">${result.summary.critical}</div><div class="stat-label">Critical</div></div>
      <div class="stat"><div class="stat-value" style="color:${severityColor.high}">${result.summary.high}</div><div class="stat-label">High</div></div>
      <div class="stat"><div class="stat-value" style="color:${severityColor.medium}">${result.summary.medium}</div><div class="stat-label">Medium</div></div>
      <div class="stat"><div class="stat-value" style="color:${severityColor.low}">${result.summary.low}</div><div class="stat-label">Low</div></div>
    </div>

    ${result.vulnerabilities.length > 0 ? `
    <h2>Vulnerabilities</h2>
    ${result.vulnerabilities.map((v) => `
    <div class="vuln-card" style="border-left-color: ${severityColor[v.severity]}">
      <div class="vuln-id">${v.id} <span class="badge" style="background:${severityColor[v.severity]}20;color:${severityColor[v.severity]}">${v.severity}</span></div>
      <div class="vuln-pkg">${v.package}@${v.version}${v.fixedIn ? ` → Fix: ${v.fixedIn}` : ""}</div>
      <div class="vuln-desc">${v.title}</div>
    </div>`).join("")}
    ` : "<h2>No Vulnerabilities Found ✓</h2>"}

    ${result.dependencies.filter(d => d.outdated).length > 0 ? `
    <h2>Outdated Dependencies</h2>
    <table>
      <thead><tr><th>Package</th><th>Current</th><th>Latest</th></tr></thead>
      <tbody>${result.dependencies.filter(d => d.outdated).map(d => `<tr><td>${d.name}</td><td>${d.version}</td><td>${d.latest}</td></tr>`).join("")}</tbody>
    </table>` : ""}

    <div class="footer">Generated by NexusForge Scanner • github.com/0xgetz/nexusforge</div>
  </div>
</body>
</html>`;
}

export function toSARIF(result: ScanResult): string {
  const sarif = {
    version: "2.1.0",
    $schema: "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0.json",
    runs: [
      {
        tool: {
          driver: {
            name: "NexusForge Scanner",
            version: "0.1.0",
            informationUri: "https://github.com/0xgetz/nexusforge",
            rules: result.vulnerabilities.map((v) => ({
              id: v.id,
              shortDescription: { text: v.title },
              fullDescription: { text: v.description },
              helpUri: v.url,
              properties: {
                severity: v.severity,
                tags: v.cwe || [],
              },
            })),
          },
        },
        results: result.vulnerabilities.map((v) => ({
          ruleId: v.id,
          message: { text: `${v.package}@${v.version}: ${v.title}` },
          level: v.severity === "critical" || v.severity === "high" ? "error" : "warning",
          locations: [
            {
              physicalLocation: {
                artifactLocation: {
                  uri: result.ecosystem === "npm" ? "package.json" : "requirements.txt",
                },
              },
            },
          ],
        })),
      },
    ],
  };

  return JSON.stringify(sarif, null, 2);
}